plugins {
    id 'com.android.application'
}

android {
    namespace 'au.com.easyai.blackcatremote'
    compileSdk 35

    defaultConfig {
        applicationId "au.com.easyai.blackcatremote"
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName "0.1"
    }
}

dependencies {}
